### ISSUE TITLE
Вопрос насчет работы

### ISSUE THREAD

**Issue by dmsrg79** [Nanografon/Scheduler#11]
Привет, ты закончил программу? Я просто изучаю код, и в некоторых контроллерах не хватает кода, ты не закончил, я правильно понимаю?

**Comment by vserpokryl** [comment]
Все верно, проект не закончен

Проект разрабатывался в рамках выпускной квалификационной работы для магистратуры, но увы, ушел я из ВУЗа гораздо раньше...
